name: Build Loader

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'File to build'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Build Loader
        run: |
          echo "Building loader with the file ${{ github.event.inputs.file }}"
          go build -o loader.exe ${{ github.event.inputs.file }}
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: loader-exe
          path: loader.exe
