name: Build and Deploy Loader

on:
  workflow_dispatch:
    inputs:
      key:
        description: 'License Key'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Build Loader
        run: |
          go build -o loader.exe loader.go
        working-directory: .

      - name: Upload Loader
        uses: actions/upload-artifact@v2
        with:
          name: loader
          path: loader.exe
