name: Build Loader

on:
  workflow_dispatch:
    inputs:
      key:
        description: 'License Key for the loader'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Inject License Key
        run: |
          echo "License Key: ${{ github.event.inputs.key }}"
          # You can use the key in your build process here

      - name: Run Build
        run: |
          go run loader.go ${{ github.event.inputs.key }}
