name: Build Loader

on:
  workflow_dispatch:
    inputs:
      key:
        description: 'License key to inject'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Find latest loader file
        id: find_loader
        run: |
          FILE=$(ls -t loader_*.go | head -n 1)
          echo "loader_file=$FILE" >> "$GITHUB_OUTPUT"

      - name: Build Windows EXE
        run: |
          GOOS=windows GOARCH=amd64 go build -o loader.exe "${{ steps.find_loader.outputs.loader_file }}"

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: loader
          path: loader.exe

      - name: Clean up - Delete .go file from GitHub
        run: |
          git rm "${{ steps.find_loader.outputs.loader_file }}"
          git commit -m "Deleted loader file after build"
          git push origin ${{ github.ref }}
